title: Sean McCahill # your name (or website title) here
logo: "/images/my_face.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><!--<xh0 style="font-family:menlo;font-size:9">01234567890123456789012345678901<x/h0> 44 numbers marks the extent of (that) text to the picture-->
  I am an entirely self-taught programmer.<br>
  <br> <!-- line 2 left empty-->
  Skills: Python, C, JavaScript, HTML, CSS<br>
  <br> <!-- line 4 left empty-->
  (323) 636-422<br>
  <br> <!-- line 6 left empty-->
  soundintime@msn.com
  <!--
  <br>  line 8 left empty
  <br>  line 9 left empty
  <br>  line 10 left empty
  <br>  line 11 left empty
  <br>  the last line to fit directly before the blurb (line 12) should be left empty
  <br>  line 13 left empty
  <br>  line 14 left empty
  <br>  it takes this many (line 15) to push github link offpage
  -->
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
