title: rowcased # your name (or website title) here
logo: "/images/my_face.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <hr>
  I am a self-taught programmer.
  <hr>
  I want to get a job writing code.
  <hr>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <!-- <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> -->
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
