title: Sean McCahill # your name (or website title) here
logo: "/images/my_face.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  line 0<br>
  I am a self-taught programmer.<br>
  line 2<br>
  Skills: Python, C, JavaScript, HTML, CSS<br>
  line 4<br>
  line 5<br>
  line 6<br>
  line 7 is different now<br>
  line 8<br>
  line 9<br>
  line 10<br>
  line 11<br>
  line 12<br>
  line 13<br>
  line 14<br>
  line 15<br>
  <!-- <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> -->
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
